package com.w8.base.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.w8.base.data.AccIp;
import com.w8.base.data.Active;
import com.w8.base.data.Chat;
import com.w8.base.data.ChatTims;
import com.w8.base.data.Computer;
import com.w8.base.data.EditeMsg;
import com.w8.base.data.Friend;
import com.w8.base.data.Frireq;
import com.w8.base.data.Group;
import com.w8.base.data.GroupFriend;
import com.w8.base.data.Smile;

import com.w8.base.data.AccIpDao;
import com.w8.base.data.ActiveDao;
import com.w8.base.data.ChatDao;
import com.w8.base.data.ChatTimsDao;
import com.w8.base.data.ComputerDao;
import com.w8.base.data.EditeMsgDao;
import com.w8.base.data.FriendDao;
import com.w8.base.data.FrireqDao;
import com.w8.base.data.GroupDao;
import com.w8.base.data.GroupFriendDao;
import com.w8.base.data.SmileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accIpDaoConfig;
    private final DaoConfig activeDaoConfig;
    private final DaoConfig chatDaoConfig;
    private final DaoConfig chatTimsDaoConfig;
    private final DaoConfig computerDaoConfig;
    private final DaoConfig editeMsgDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig frireqDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig groupFriendDaoConfig;
    private final DaoConfig smileDaoConfig;

    private final AccIpDao accIpDao;
    private final ActiveDao activeDao;
    private final ChatDao chatDao;
    private final ChatTimsDao chatTimsDao;
    private final ComputerDao computerDao;
    private final EditeMsgDao editeMsgDao;
    private final FriendDao friendDao;
    private final FrireqDao frireqDao;
    private final GroupDao groupDao;
    private final GroupFriendDao groupFriendDao;
    private final SmileDao smileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accIpDaoConfig = daoConfigMap.get(AccIpDao.class).clone();
        accIpDaoConfig.initIdentityScope(type);

        activeDaoConfig = daoConfigMap.get(ActiveDao.class).clone();
        activeDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        chatTimsDaoConfig = daoConfigMap.get(ChatTimsDao.class).clone();
        chatTimsDaoConfig.initIdentityScope(type);

        computerDaoConfig = daoConfigMap.get(ComputerDao.class).clone();
        computerDaoConfig.initIdentityScope(type);

        editeMsgDaoConfig = daoConfigMap.get(EditeMsgDao.class).clone();
        editeMsgDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        frireqDaoConfig = daoConfigMap.get(FrireqDao.class).clone();
        frireqDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        groupFriendDaoConfig = daoConfigMap.get(GroupFriendDao.class).clone();
        groupFriendDaoConfig.initIdentityScope(type);

        smileDaoConfig = daoConfigMap.get(SmileDao.class).clone();
        smileDaoConfig.initIdentityScope(type);

        accIpDao = new AccIpDao(accIpDaoConfig, this);
        activeDao = new ActiveDao(activeDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);
        chatTimsDao = new ChatTimsDao(chatTimsDaoConfig, this);
        computerDao = new ComputerDao(computerDaoConfig, this);
        editeMsgDao = new EditeMsgDao(editeMsgDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        frireqDao = new FrireqDao(frireqDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        groupFriendDao = new GroupFriendDao(groupFriendDaoConfig, this);
        smileDao = new SmileDao(smileDaoConfig, this);

        registerDao(AccIp.class, accIpDao);
        registerDao(Active.class, activeDao);
        registerDao(Chat.class, chatDao);
        registerDao(ChatTims.class, chatTimsDao);
        registerDao(Computer.class, computerDao);
        registerDao(EditeMsg.class, editeMsgDao);
        registerDao(Friend.class, friendDao);
        registerDao(Frireq.class, frireqDao);
        registerDao(Group.class, groupDao);
        registerDao(GroupFriend.class, groupFriendDao);
        registerDao(Smile.class, smileDao);
    }
    
    public void clear() {
        accIpDaoConfig.clearIdentityScope();
        activeDaoConfig.clearIdentityScope();
        chatDaoConfig.clearIdentityScope();
        chatTimsDaoConfig.clearIdentityScope();
        computerDaoConfig.clearIdentityScope();
        editeMsgDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
        frireqDaoConfig.clearIdentityScope();
        groupDaoConfig.clearIdentityScope();
        groupFriendDaoConfig.clearIdentityScope();
        smileDaoConfig.clearIdentityScope();
    }

    public AccIpDao getAccIpDao() {
        return accIpDao;
    }

    public ActiveDao getActiveDao() {
        return activeDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public ChatTimsDao getChatTimsDao() {
        return chatTimsDao;
    }

    public ComputerDao getComputerDao() {
        return computerDao;
    }

    public EditeMsgDao getEditeMsgDao() {
        return editeMsgDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public FrireqDao getFrireqDao() {
        return frireqDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public GroupFriendDao getGroupFriendDao() {
        return groupFriendDao;
    }

    public SmileDao getSmileDao() {
        return smileDao;
    }

}
