package com.w8.base.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EDITE_MSG".
*/
public class EditeMsgDao extends AbstractDao<EditeMsg, Long> {

    public static final String TABLENAME = "EDITE_MSG";

    /**
     * Properties of entity EditeMsg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Txt = new Property(2, String.class, "txt", false, "TXT");
        public final static Property Tim = new Property(3, long.class, "tim", false, "TIM");
    }


    public EditeMsgDao(DaoConfig config) {
        super(config);
    }
    
    public EditeMsgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EDITE_MSG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"UUID\" TEXT NOT NULL ," + // 1: uuid
                "\"TXT\" TEXT NOT NULL ," + // 2: txt
                "\"TIM\" INTEGER NOT NULL );"); // 3: tim
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_EDITE_MSG_UUID ON \"EDITE_MSG\"" +
                " (\"UUID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EDITE_MSG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EditeMsg entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getUuid());
        stmt.bindString(3, entity.getTxt());
        stmt.bindLong(4, entity.getTim());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EditeMsg entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getUuid());
        stmt.bindString(3, entity.getTxt());
        stmt.bindLong(4, entity.getTim());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EditeMsg readEntity(Cursor cursor, int offset) {
        EditeMsg entity = new EditeMsg( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // uuid
            cursor.getString(offset + 2), // txt
            cursor.getLong(offset + 3) // tim
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EditeMsg entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.getString(offset + 1));
        entity.setTxt(cursor.getString(offset + 2));
        entity.setTim(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EditeMsg entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EditeMsg entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EditeMsg entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
