package com.w8.base.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRIREQ".
*/
public class FrireqDao extends AbstractDao<Frireq, Long> {

    public static final String TABLENAME = "FRIREQ";

    /**
     * Properties of entity Frireq.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Requid = new Property(1, String.class, "requid", false, "REQUID");
        public final static Property Resuid = new Property(2, String.class, "resuid", false, "RESUID");
        public final static Property Reqaccount = new Property(3, String.class, "reqaccount", false, "REQACCOUNT");
        public final static Property Reqnickname = new Property(4, String.class, "reqnickname", false, "REQNICKNAME");
        public final static Property Reqdes = new Property(5, String.class, "reqdes", false, "REQDES");
        public final static Property Tim = new Property(6, long.class, "tim", false, "TIM");
        public final static Property Met = new Property(7, String.class, "met", false, "MET");
        public final static Property Typ = new Property(8, int.class, "typ", false, "TYP");
    }


    public FrireqDao(DaoConfig config) {
        super(config);
    }
    
    public FrireqDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIREQ\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"REQUID\" TEXT NOT NULL ," + // 1: requid
                "\"RESUID\" TEXT NOT NULL ," + // 2: resuid
                "\"REQACCOUNT\" TEXT NOT NULL ," + // 3: reqaccount
                "\"REQNICKNAME\" TEXT NOT NULL ," + // 4: reqnickname
                "\"REQDES\" TEXT NOT NULL ," + // 5: reqdes
                "\"TIM\" INTEGER NOT NULL ," + // 6: tim
                "\"MET\" TEXT NOT NULL ," + // 7: met
                "\"TYP\" INTEGER NOT NULL );"); // 8: typ
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIREQ\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Frireq entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getRequid());
        stmt.bindString(3, entity.getResuid());
        stmt.bindString(4, entity.getReqaccount());
        stmt.bindString(5, entity.getReqnickname());
        stmt.bindString(6, entity.getReqdes());
        stmt.bindLong(7, entity.getTim());
        stmt.bindString(8, entity.getMet());
        stmt.bindLong(9, entity.getTyp());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Frireq entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getRequid());
        stmt.bindString(3, entity.getResuid());
        stmt.bindString(4, entity.getReqaccount());
        stmt.bindString(5, entity.getReqnickname());
        stmt.bindString(6, entity.getReqdes());
        stmt.bindLong(7, entity.getTim());
        stmt.bindString(8, entity.getMet());
        stmt.bindLong(9, entity.getTyp());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Frireq readEntity(Cursor cursor, int offset) {
        Frireq entity = new Frireq( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // requid
            cursor.getString(offset + 2), // resuid
            cursor.getString(offset + 3), // reqaccount
            cursor.getString(offset + 4), // reqnickname
            cursor.getString(offset + 5), // reqdes
            cursor.getLong(offset + 6), // tim
            cursor.getString(offset + 7), // met
            cursor.getInt(offset + 8) // typ
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Frireq entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRequid(cursor.getString(offset + 1));
        entity.setResuid(cursor.getString(offset + 2));
        entity.setReqaccount(cursor.getString(offset + 3));
        entity.setReqnickname(cursor.getString(offset + 4));
        entity.setReqdes(cursor.getString(offset + 5));
        entity.setTim(cursor.getLong(offset + 6));
        entity.setMet(cursor.getString(offset + 7));
        entity.setTyp(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Frireq entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Frireq entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Frireq entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
