package com.w8.base.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_FRIEND".
*/
public class GroupFriendDao extends AbstractDao<GroupFriend, Long> {

    public static final String TABLENAME = "GROUP_FRIEND";

    /**
     * Properties of entity GroupFriend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Gid = new Property(1, String.class, "gid", false, "GID");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
        public final static Property Uaccount = new Property(3, String.class, "uaccount", false, "UACCOUNT");
        public final static Property Uremark = new Property(4, String.class, "uremark", false, "UREMARK");
    }


    public GroupFriendDao(DaoConfig config) {
        super(config);
    }
    
    public GroupFriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_FRIEND\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"GID\" TEXT NOT NULL ," + // 1: gid
                "\"UID\" TEXT NOT NULL ," + // 2: uid
                "\"UACCOUNT\" TEXT NOT NULL ," + // 3: uaccount
                "\"UREMARK\" TEXT NOT NULL );"); // 4: uremark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_FRIEND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupFriend entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getGid());
        stmt.bindString(3, entity.getUid());
        stmt.bindString(4, entity.getUaccount());
        stmt.bindString(5, entity.getUremark());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupFriend entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getGid());
        stmt.bindString(3, entity.getUid());
        stmt.bindString(4, entity.getUaccount());
        stmt.bindString(5, entity.getUremark());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupFriend readEntity(Cursor cursor, int offset) {
        GroupFriend entity = new GroupFriend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // gid
            cursor.getString(offset + 2), // uid
            cursor.getString(offset + 3), // uaccount
            cursor.getString(offset + 4) // uremark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupFriend entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGid(cursor.getString(offset + 1));
        entity.setUid(cursor.getString(offset + 2));
        entity.setUaccount(cursor.getString(offset + 3));
        entity.setUremark(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupFriend entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupFriend entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupFriend entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
