package com.w8.base.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SMILE".
*/
public class SmileDao extends AbstractDao<Smile, Long> {

    public static final String TABLENAME = "SMILE";

    /**
     * Properties of entity Smile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Fnum = new Property(1, int.class, "fnum", false, "FNUM");
        public final static Property Sname = new Property(2, String.class, "sname", false, "SNAME");
    }


    public SmileDao(DaoConfig config) {
        super(config);
    }
    
    public SmileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SMILE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"FNUM\" INTEGER NOT NULL ," + // 1: fnum
                "\"SNAME\" TEXT NOT NULL );"); // 2: sname
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SMILE_FNUM ON \"SMILE\"" +
                " (\"FNUM\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SMILE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Smile entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getFnum());
        stmt.bindString(3, entity.getSname());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Smile entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getFnum());
        stmt.bindString(3, entity.getSname());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Smile readEntity(Cursor cursor, int offset) {
        Smile entity = new Smile( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getInt(offset + 1), // fnum
            cursor.getString(offset + 2) // sname
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Smile entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFnum(cursor.getInt(offset + 1));
        entity.setSname(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Smile entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Smile entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Smile entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
